# Generated by Django 3.2.7 on 2021-09-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date_bought',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='bought_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_sold',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sold_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], default='Buy', max_length=4),
        ),
    ]
