# Generated by Django 3.2.7 on 2021-09-16 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=13),
        ),
        migrations.CreateModel(
            name='OwnStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('quantity', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
